version: "2"

services:
  reader:
    build: ./reader
    environment:
      - TwitterConsumerKey
      - TwitterConsumerSecret
      - TwitterAccessToken
      - TwitterAccessTokenSecret

  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports: 
     - "8080:15672"

  analyzer:
    build: ./analyzer
    environment:
      - TextAnalyticsApiKey

  aggregator:
    build: ./aggregator

  redis:
    image: redis:4.0.10-alpine

  result:
    build: ./result
    ports: 
      - "4000:80"
